[package]
name = "radio"
version = "0.1.0"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
wasm-bindgen = "0.2.55"
enclose = "^1.1.6"
strum = "0.17.1"
strum_macros = "0.17.1"
