[package]
name = "drop_zone"
version = "0.1.0"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
wasm-bindgen-futures = "0.4.13"
gloo-file = { version = "0.1.0", features = ["futures"] }
