extend = "../../Makefile.toml"

[tasks.install]
command = "yarn"
args = ["install"]

[tasks.clean]
command = "rm"
args = ["-rf", "pkg", "service-worker.js"]

[tasks.inject_manifest]
command = "yarn"
args = ["run", "inject_manifest"]

# ---- BUILD ----

[tasks.build]
dependencies = ["install", "clean", "default_build", "inject_manifest"]

[tasks.build_release]
alias = "default_build_release"

# ---- START ----

[tasks.start]
alias = "default_start"
dependencies = ["build"]

[tasks.start_release]
alias = "default_start_release"

# ---- LINT ----

[tasks.clippy]
alias = "default_clippy"
