extend = "../../Makefile.toml"

[tasks.clean]
command = "cargo"
args = ["clean", "--target-dir", "pkg"]

# ---- BUILD ----

[tasks.build]
dependencies = ["clean", "default_build"]

[tasks.build_release]
alias = "default_build_release"

# ---- START ----

[tasks.start]
alias = "default_start"
dependencies = ["build"]

[tasks.start_release]
alias = "default_start_release"

# ---- LINT ----

[tasks.clippy]
alias = "default_clippy"
